### ISSUE TITLE
There are missing data in the Dashboard (Cluster & Datastore)

### ISSUE THREAD

**Issue by oijkn** [jorgedlcruz/vmware-grafana#26]
### Relevant telegraf.conf:

```toml
## Realtime instance
[[inputs.vsphere]]
## List of vCenter URLs to be monitored. These three lines must be uncommented
## and edited for the plugin to work.
  interval = "20s"
  vcenters = [ "https://10.1.x.x/sdk" ]
  username = "user@vsphere.local"
  password = "pass"

  vm_metric_include = []
  host_metric_include = []
  cluster_metric_include = []
  datastore_metric_exclude = ["*"]

  max_query_metrics = 256
  timeout = "120s"
  insecure_skip_verify = true

## Historical instance
[[inputs.vsphere]]
  interval = "300s"
  vcenters = [ "https://10.1.x.x/sdk" ]
  username = "user@vsphere.local"
  password = "pass"

  datastore_metric_include = [ "disk.capacity.latest", "disk.used.latest", "disk.provisioned.latest"]
  insecure_skip_verify = true
  force_discover_on_init = true
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  max_query_metrics = 256
  collect_concurrency = 3
```

### System info:

```
[root@centos]: $ cat /etc/*-release | grep "VERSION="
VERSION="8 (Core)"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

[root@centos]: $ telegraf --version
Telegraf 1.15.3 (git: HEAD fac81815)

[root@centos]: $ grafana-server -v
Version 7.2.0 (commit: efe4941ee3, branch: HEAD)

[root@centos]: $ influx --version
InfluxDB shell version: 1.8.3
```

### Expected behavior:

- Display the number of clusters available in the overview dash
- View Datastore ReadAverage & WriteAverage metrics

### Actual behavior:

- Nothing is displayed on the Dashboard

### Additional info:

**Query for number of cluster:**
`SELECT count(distinct("clustername")) AS "Cluster" FROM (SELECT "totalmhz_average", "clustername" FROM  "vsphere_cluster_cpu" WHERE $timeFilter)`

**Query for ReadAverage & WriteAverage:**
`SELECT mean("numberReadAveraged_average") FROM "vsphere_datastore_datastore" WHERE ("source" =~ /^$datastore$/) AND $timeFilter GROUP BY time(5m), "source" fill(none)`

```
Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> use telegraf
Using database telegraf
> show measurements
name: measurements
name
----
vsphere_cluster_clusterServices
vsphere_cluster_mem
vsphere_cluster_vmop
vsphere_datacenter_vmop
vsphere_datastore_disk
vsphere_host_cpu
vsphere_host_datastore
vsphere_host_disk
vsphere_host_hbr
vsphere_host_mem
vsphere_host_net
vsphere_host_power
vsphere_host_rescpu
vsphere_host_storageAdapter
vsphere_host_storagePath
vsphere_host_sys
vsphere_host_vflashModule
vsphere_vm_cpu
vsphere_vm_datastore
vsphere_vm_disk
vsphere_vm_mem
vsphere_vm_net
vsphere_vm_power
vsphere_vm_rescpu
vsphere_vm_sys
vsphere_vm_virtualDisk
```
As you can see no measurement exists with the name _vsphere_cluster_cpu_ or _vsphere_datastore_datastore_.

Can you look on your side and fix this please ? Gracias por tu ayuda :)

BR.
